/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export enum AccountTestCreationDataEmailState {
    Missing = "missing",
    Unverified = "unverified",
    Verified = "verified",
}

export enum AccountTestCreationDataPhoneState {
    Missing = "missing",
    Unverified = "unverified",
    Verified = "verified",
}

export class AccountTestCreationDataInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deactivate_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deactivateAt: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "email_state" })
    emailState: AccountTestCreationDataEmailState;

    @SpeakeasyMetadata()
    @Expose({ name: "has_address" })
    hasAddress?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "is_migrated" })
    isMigrated?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_state" })
    phoneState: AccountTestCreationDataPhoneState;
}

export class AccountTestCreationDataOutput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deactivate_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deactivateAt: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    @SpeakeasyMetadata()
    @Expose({ name: "email_state" })
    emailState: AccountTestCreationDataEmailState;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_code" })
    oauthCode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "otp_code" })
    otpCode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_state" })
    phoneState: AccountTestCreationDataPhoneState;
}
