/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of address reference
 */
export enum AddressReferenceIdTag {
    Id = "id",
}

export class AddressReferenceId extends SpeakeasyBase {
    /**
     * The type of address reference
     */
    @SpeakeasyMetadata()
    @Expose({ name: ".tag" })
    dotTag: AddressReferenceIdTag;

    /**
     * The address's ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}
