/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Amounts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: string;

    /**
     * The total tax amount, in cents for all of the items associated with the cart.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax" })
    tax?: number;

    /**
     * The total amount, in cents, including its items and taxes (if applicable).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
