/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CallbackUrls extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "account_page" })
    accountPage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "base_domain" })
    baseDomain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "confirmation_redirect" })
    confirmationRedirect?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "create_order" })
    createOrder?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "debug" })
    debug?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "get_account" })
    getAccount?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "mobile_app_domain" })
    mobileAppDomain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_logout" })
    oauthLogout?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_redirect" })
    oauthRedirect?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "privacy_policy" })
    privacyPolicy?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_info" })
    productInfo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "remote_api" })
    remoteApi?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shipping" })
    shipping?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "support_page" })
    supportPage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tax" })
    tax?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "terms_of_service" })
    termsOfService?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "universal_merchant_api" })
    universalMerchantApi?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "update_cart" })
    updateCart?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "validate_additional_account_data" })
    validateAdditionalAccountData?: string;
}
