/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Amounts } from "./amounts";
import { CartDiscount } from "./cartdiscount";
import { CartItem } from "./cartitem";
import { CartShipmentInput } from "./cartshipment";
import { Expose, Type } from "class-transformer";

export class CartInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amounts" })
    @Type(() => Amounts)
    amounts: Amounts;

    @SpeakeasyMetadata({ elemType: CartDiscount })
    @Expose({ name: "discounts" })
    @Type(() => CartDiscount)
    discounts?: CartDiscount[];

    /**
     * This field corresponds to the merchant's order reference associated with this Bolt transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_id" })
    displayId?: string;

    @SpeakeasyMetadata({ elemType: CartItem })
    @Expose({ name: "items" })
    @Type(() => CartItem)
    items?: CartItem[];

    /**
     * Used optionally to pass additional information like order numbers or other IDs as needed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_description" })
    orderDescription?: string;

    /**
     * This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_reference" })
    orderReference: string;

    @SpeakeasyMetadata({ elemType: CartShipmentInput })
    @Expose({ name: "shipments" })
    @Type(() => CartShipmentInput)
    shipments?: CartShipmentInput[];
}
