/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CartItem extends SpeakeasyBase {
    /**
     * A human-readable description of this cart item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Used to provide a link to the image associated with the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "image_url" })
    imageUrl?: string;

    /**
     * The name of a given item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The number of units that comprise this cart item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * This value is used by Bolt as an external reference to a given item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reference" })
    reference: string;

    /**
     * The total amount, in cents, of the item including its taxes if applicable.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount: number;

    /**
     * The price of one unit of the item; for example, the price of one pack of socks.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_price" })
    unitPrice: number;
}
