/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Amounts } from "./amounts";
import { Expose, Type } from "class-transformer";

export class CartShipmentInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: any;

    /**
     * The name of the carrier selected.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "carrier" })
    carrier?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cost" })
    @Type(() => Amounts)
    cost?: Amounts;
}
