/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The credit card network.
 */
export enum CreditCardNetwork {
    Visa = "visa",
    Mastercard = "mastercard",
    Amex = "amex",
    Discover = "discover",
    Jcb = "jcb",
    Unionpay = "unionpay",
    Alliancedata = "alliancedata",
    Citiplcc = "citiplcc",
}

export class CreditCardOutput extends SpeakeasyBase {
    /**
     * The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiration" })
    expiration: string;

    /**
     * The last 4 digits of the credit card number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4" })
    last4: string;

    /**
     * The credit card network.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "network" })
    network: CreditCardNetwork;
}
