/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class IdentifiersMerchantDivisions extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "publishable_key" })
    publishableKey: string;
}

export class Identifiers extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: IdentifiersMerchantDivisions })
    @Expose({ name: "merchant_divisions" })
    @Type(() => IdentifiersMerchantDivisions)
    merchantDivisions: IdentifiersMerchantDivisions[];

    @SpeakeasyMetadata()
    @Expose({ name: "merchant_id" })
    merchantId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "signing_secret" })
    signingSecret: string;
}
