/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PaymentMethodSavedPaymentMethodTag {
    SavedPaymentMethod = "saved_payment_method",
}

export class PaymentMethodSavedPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: ".tag" })
    dotTag: PaymentMethodSavedPaymentMethodTag;

    /**
     * Payment ID of the saved Bolt Payment method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}
