/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CartInput } from "./cart";
import { Expose, Type } from "class-transformer";

export class PaymentMethodInitializeRequestInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => CartInput)
    cart: CartInput;

    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    paymentMethod: any;
}
