/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PaymentMethodPaypalTag {
    Paypal = "paypal",
}

export class PaymentMethodPaypal extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: ".tag" })
    dotTag: PaymentMethodPaypalTag;

    /**
     * Redirect URL for canceled PayPal transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cancel" })
    cancel: string;

    /**
     * Redirect URL for successful PayPal transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success: string;
}
