/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The shipment's status.
 */
export enum ShipmentTrackingUpdateStatus {
    InTransit = "in_transit",
    Cancelled = "cancelled",
    Failure = "failure",
    Delivered = "delivered",
}

export enum ShipmentTrackingUpdateTrackingDetailsStatus {
    Unknown = "unknown",
    PreTransit = "pre_transit",
    InTransit = "in_transit",
    OutForDelivery = "out_for_delivery",
    Delivered = "delivered",
    AvailableForPickup = "available_for_pickup",
    ReturnToSender = "return_to_sender",
    Failure = "failure",
    Cancelled = "cancelled",
    Error = "error",
}

export class ShipmentTrackingUpdateTrackingDetails extends SpeakeasyBase {
    /**
     * The country associated this this set of tracking details, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode?: string;

    /**
     * The tracking detail's timestamp.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_date" })
    eventDate?: string;

    /**
     * The locality associated this this set of tracking details, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "locality" })
    locality?: string;

    /**
     * An arbitrary, human-readable message associated with this set of tracking details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * The postal associated this this set of tracking details, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode?: string;

    /**
     * The region associated this this set of tracking details, if any.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: ShipmentTrackingUpdateTrackingDetailsStatus;
}

export class ShipmentTrackingUpdate extends SpeakeasyBase {
    /**
     * The shipment's actual or estimated delivery date.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delivery_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deliveryDate?: Date;

    /**
     * The shipment's status.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: ShipmentTrackingUpdateStatus;

    /**
     * A list of tracking updates that contain the shipment's status, location, and any unique messages.
     */
    @SpeakeasyMetadata({ elemType: ShipmentTrackingUpdateTrackingDetails })
    @Expose({ name: "tracking_details" })
    @Type(() => ShipmentTrackingUpdateTrackingDetails)
    trackingDetails: ShipmentTrackingUpdateTrackingDetails[];

    /**
     * The carrier's tracking number for the shipment. Must be prefixed with `MockBolt`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tracking_number" })
    trackingNumber: string;
}
