/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class Webhook extends SpeakeasyBase {
    /**
     * The time at which the webhook was created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event: any;

    /**
     * The webhook's ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The webhook's URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}

export class WebhookInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event: any;

    /**
     * The webhook's URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
